locales:
  available: ["en", "vi"]
  default: "en"
users:
  name:
    max_length: 100
  email:
    max_length: 255
  password:
    min_length: 6
  paginate:
    per_page: 30
  phone:
    min_length: 10
    max_length: 11
cates:
  paginate:
    per_page: 20
products:
  paginate:
    per_page: 20
  paginate_default: 8
gravatar:
  default_size: 200
  size_30: 30
